GRANT SELECT ON SGC.SGC_CRE_CREDITOS TO PA;
GRANT SELECT ON SGC.SGC_EST_ESTADO TO PA;
GRANT SELECT ON SGC.SGC_RES_RESERVA TO PA;
GRANT SELECT ON SGC.SGC_CLI_CLIENTE_HONRADO TO PA;
GRANT SELECT ON SGC.SGC_CHO_CODEUDOR_HONRA TO PA;
GRANT SELECT ON PR.PR_CREDITOS TO PA;
GRANT SELECT ON PR.PR_ESTADOS_CREDITO TO PA;
GRANT SELECT ON CR.CR_CREDITOS TO PA;
GRANT SELECT ON CR.CR_ESTADOS_CREDITO TO PA;
GRANT SELECT ON CR.cr_garantias TO PA;
GRANT SELECT ON CR.cr_garantias_x_credito TO PA;
GRANT SELECT ON BVA_B2000.VA_VENTAS_CONTRI TO PA;
GRANT SELECT ON BVA_B2000.VA_VENTAS_CONSUM TO PA;
GRANT SELECT ON BVA_B2000.VA_COMPRAS TO PA;
GRANT SELECT ON CV.BCV_DOCUMENTOS TO PA;
GRANT SELECT ON CV.BCV_TIPOS_DE_DOCUMENTOS TO PA;
GRANT SELECT ON CTC.CTC_PERSONAS TO PA;


